{% set version = "5.0.20200914.2323" %}
{% set git_rev = "cdd49013b63aa72cb3343ff14fd66d5f88b0182f" %}

package:
  name: mantid-framework
  version: {{ version }}

source:
  git_rev: {{ git_rev }}
  git_url: https://github.com/mantidproject/mantid.git

requirements:
  build:
    - blas
    - boost
    - cmake
    - eigen
    - gsl
    - gxx_linux-64 8.* [linux64]
    - h5py
    - hdf4
    - hdf5
    - jemalloc
    - jsoncpp
    - librdkafka
    - muparser
    - nexus
    - ninja
    - numpy {{ numpy }}
    - openblas
    - openssl
    - pkg-config
    - poco
    - python {{ python }}
    - tbb-devel

  run:
    - boost
    - h5py
    - librdkafka
    - nexus
    - numpy
    - poco
    - python
    - python-dateutil
    - pyyaml
    - scipy
    - six
    - tbb
    - gsl

build:
  script_env:
    - CC
    - CXX
    - OSX_VERSION

test:
  immports:
    mantid.kernel
    mantid.geometry
    mantid.api
    mantid.simpleapi

about:
  home:
  license:
  license_file:
