{% set version = "5.1.20201218.1546" %}
{% set git_rev = "6149d0d57fdef374c743cc70c19753f1c775a178" %}

package:
  name: mantid-framework
  version: {{ version }}

source:
  git_rev: {{ git_rev }}
  git_url: https://github.com/mantidproject/mantid.git

requirements:
  build:
    - blas
    - boost
    - cmake
    - eigen
    - gsl
    - gxx_linux-64 8.* [linux64]
    - h5py
    - hdf4
    - hdf5
    - jemalloc
    - jsoncpp
    - librdkafka
    - muparser
    - nexus
    - ninja
    - numpy {{ numpy }}
    - openblas
    - openssl
    - pkg-config
    - poco
    - python {{ python }}
    - tbb-devel

  run:
    - boost
    - h5py
    - librdkafka
    - nexus
    - numpy {{ numpy }}
    - poco
    - python {{ python }}
    - python-dateutil
    - pyyaml
    - scipy
    - six
    - tbb
    - gsl
    - jsoncpp
    - muparser
    - mkl

build:
  script_env:
    - CC
    - CXX
    - OSX_VERSION

test:
  imports:
    - mantid.kernel
    - mantid.geometry
    - mantid.api

about:
  home:
  license:
  license_file:
