parameters:
  - name: publish
    type: boolean
    default: false

jobs:
  - job: 'linux'
    displayName: 'Linux'
    timeoutInMinutes: 120
    strategy:
      matrix:
        Python37:
          PYTHON_VERSION: '3.7'
    pool:
      vmImage: 'ubuntu-latest'
    variables:
      - group: tokens
    steps:
      - checkout: self
        submodules: true
      - bash: | 
          echo "##vso[task.prependpath]$CONDA/bin"
        displayName: 'add conda to PATH'
      - bash: |
          set -ex
          conda --version
          conda install --yes anaconda-client conda-build
          conda config --set always_yes yes --set changeps1 no
        displayName: 'Conda configuration'
      - ${{ if eq(parameters.publish, true) }}:
        - bash: |
            echo publishing "${{ parameters.publish }}"
              echo Publishing
              #conda build --user scipp --token "$ANACONDA_TOKEN" --channel conda-forge --label main --python="$PYTHON_VERSION" .
          env:
            ANACONDA_TOKEN: $(anaconda_token_secret)
          displayName: 'Package build'
      - ${{ if not(eq(parameters.publish, true)) }}:
        - bash: |
            else
              echo Building without publishing
              #conda build --channel conda-forge --python="$PYTHON_VERSION" .
            fi
          displayName: 'Package build'
