pr:
  autoCancel: true
  branches:
    include:
      - '*'
trigger: none

extends:
  template: templates/build_and_package.yml
  parameters:
    publish: false # Do not publish package to anaconda cloud 
    git_rev: "master"
    mantid_ver: "5.1.x" # unknown 
