trigger:
  tags:
    include:
      - '*.*.*'

pr: none

extends:
  template: templates/build_and_package.yml
  parameters:
    publish: true #  publish package to anaconda cloud
    git_rev: "46a08124a610869112b890123bb3a4c5e14486e7"
    mantid_ver: "6.0.20210412.0948" # calculated from tools/make_version.py/
