trigger:
  tags:
    include:
      - '*.*.*'

pr: none

extends:
  template: templates/build_and_package.yml
  parameters:
    publish: false # Do not publish package 

stages:

  - stage: 'build_conda_package'
    displayName: 'Build Conda Package'
    jobs:
      - template: templates/build_and_package.yml
