trigger:
  tags:
    include:
      - '*.*.*'

pr: none

stages:

  - stage: 'build_conda_package'
    displayName: 'Build Conda Package'

    jobs:
      - job: 'linux'
        displayName: 'Linux'
        timeoutInMinutes: 60
        pool:
          vmImage: 'ubuntu-18.04'
        variables:
          - group: tokens
        steps:
          - checkout: self
            submodules: true
          - bash: echo "##vso[task.prependpath]$CONDA/bin"
            displayName: 'add conda to PATH'
          - bash: |
              set -ex
              conda --version
              conda install --yes anaconda-client conda-build
              conda config --set always_yes yes --set changeps1 no
              conda env create -f env37.yml
              source activate env
            displayName: 'Conda configuration'
          - bash: |
              conda build --user scipp --token "$ANACONDA_TOKEN" --channel conda-forge .
            env:
              ANACONDA_TOKEN: $(anaconda_token_secret)
            displayName: 'Package build'
          - task: PublishBuildArtifacts@1
            inputs:
              PathtoPublish: "$(conda_dir)/conda-bld/linux-64"
              ArtifactName: 'linux-64'
            displayName: 'Publish Conda package artefacts'
