trigger:
  tags:
    include:
      - '*.*.*'

pr: none

extends:
  template: templates/build_and_package.yml
  parameters:
    publish: true #  publish package to anaconda cloud
    git_rev: "bdfad1bdf752d9bc5035491fe6a2927494644c5f"
    mantid_ver: "6.0.20210317.2323" # calculated from tools/make_version.py/
